export const LISTENER_STATUS_OFFLINE = 'OFFLINE';
export const LISTENER_STATUS_WAITING = 'WAITING';
export const LISTENER_STATUS_IMMINENT = 'IMMINENT';
export const LISTENER_STATUS_RELEASING = 'RELEASING';
